// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Region$ReactHooksTemplate = require("../src/types/Region.js");

Jest.describe("Region", (function (param) {
        Jest.test("toCsvString", (function (param) {
                return Jest.Expect[/* toBe */2]("na,lan", Jest.Expect[/* expect */0](Region$ReactHooksTemplate.toCsvString(/* :: */[
                                    /* NorthAmerica */1,
                                    /* :: */[
                                      /* LatinNorthAmerica */5,
                                      /* [] */0
                                    ]
                                  ])));
              }));
        return Jest.test("toCsvString all", (function (param) {
                      return Jest.Expect[/* toBe */2]("na,kr,euw,eune,lan,las,br,jp,tr,ru,oce", Jest.Expect[/* expect */0](Region$ReactHooksTemplate.toCsvString(Region$ReactHooksTemplate.list)));
                    }));
      }));

/*  Not a pure module */
