// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict'

var React = require('react')
var ChampIcon = require('./ChampIcon.js')
var Pervasives = require('bs-platform/lib/js/pervasives.js')
var ReasonReact = require('reason-react/src/ReasonReact.js')

var component = ReasonReact.statelessComponent('Champion')

function make(name, number, handleImageLoad, _) {
    var newrecord = component.slice()
    newrecord[/* render */ 9] = function() {
        var len = Pervasives.string_of_int(number).length
        var digitStr = (len === 1 ? 'one' : 'two') + '-digit'
        var numberStyle = 'number-text ' + digitStr
        return React.createElement(
            'div',
            {
                className: 'champ-square',
            },
            React.createElement(
                'div',
                {
                    className: 'overlay',
                },
                React.createElement(
                    'span',
                    {
                        className: numberStyle,
                    },
                    Pervasives.string_of_int(number),
                ),
            ),
            ReasonReact.element(
                /* None */ 0,
                /* None */ 0,
                ChampIcon.make(
                    name,
                    /* false */ 0,
                    handleImageLoad,
                    /* array */ [],
                ),
            ),
        )
    }
    return newrecord
}

exports.component = component
exports.make = make
/* component Not a pure module */
