// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict'

var Curry = require('bs-platform/lib/js/curry.js')
var React = require('react')
var ReasonReact = require('reason-react/src/ReasonReact.js')

var component = ReasonReact.statelessComponent('ChampIcon')

var getIcon = function(name) {
    try {
        return require(`../../assets/champ-icons/min/${name.toLowerCase()}square-min.png`)
    } catch (ex) {
        return require('../../assets/champ-icons/min/questionmark.png')
    }
}

function make(name, mini, handleImageLoad, _) {
    var newrecord = component.slice()
    newrecord[/* render */ 9] = function() {
        var miniCN = mini ? 'mini-' : ''
        var imgCN = miniCN + 'champ-icon'
        var championIconPath = Curry._1(getIcon, name)
        return React.createElement('img', {
            className: imgCN,
            alt: name + ' One Trick Pony/Ponies',
            src: championIconPath,
            onLoad: handleImageLoad,
        })
    }
    return newrecord
}

var $$default = ReasonReact.wrapReasonForJs(component, function(jsProps) {
    return make(
        jsProps.name,
        jsProps.mini,
        jsProps.handleImageLoad,
        jsProps.children,
    )
})

exports.component = component
exports.getIcon = getIcon
exports.make = make
exports.$$default = $$default
exports.default = $$default
exports.__esModule = true
/* component Not a pure module */
