// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array     = require("bs-platform/lib/js/array.js");
var Curry       = require("bs-platform/lib/js/curry.js");
var React       = require("react");
var Champion    = require("./Champion.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("ChampionPane");

function make(champions, getPlayers, handleImageLoad) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "champs"
                }, $$Array.map((function (param) {
                        var championName = param[0];
                        return React.createElement("a", {
                                    key: championName,
                                    className: "champ-open-links fade-in",
                                    href: "#",
                                    onClick: (function () {
                                        return Curry._1(getPlayers, /* tuple */[
                                                    champions,
                                                    championName
                                                  ]);
                                      })
                                  }, ReasonReact.element(/* Some */[championName], /* None */0, Champion.make(championName, param[1].length, handleImageLoad, /* array */[])));
                      }), champions));
    });
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.champions, jsProps.getPlayers, jsProps.handleImageLoad);
      }));

exports.component = component;
exports.make      = make;
exports.$$default = $$default;
exports.default   = $$default;
exports.__esModule= true;
/* component Not a pure module */
