// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Copyright");

var disclaimerEl = "This product isn't endorsed by Riot Games and doesn't reflect the views or opinions of Riot Games or anyone officially involved in producing or managing League of Legends. League of Legends and Riot Games are trademarks or registered trademarks of Riot Games, Inc.\nLeague of Legends \xc2\xa9 Riot Games,Inc. This product is not endorsed, certified\nor otherwise approved in any way by op.gg, and lolking or any of their\naffiliates. All game data is powered by Riot's API. ";

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "copyright"
                }, disclaimerEl, React.createElement("a", {
                      id: "src-code",
                      href: "https://github.com/ChauTNguyen/OneTricks",
                      rel: "noopener noreferrer",
                      target: "_blank"
                    }, "src code"));
    });
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, (function () {
        return make(/* () */0);
      }));

exports.component    = component;
exports.disclaimerEl = disclaimerEl;
exports.make         = make;
exports.$$default    = $$default;
exports.default      = $$default;
exports.__esModule   = true;
/* component Not a pure module */
