// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List        = require("bs-platform/lib/js/list.js");
var $$Array     = require("bs-platform/lib/js/array.js");
var React       = require("react");
var $$String    = require("bs-platform/lib/js/string.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("FilterBtn");

function make(onClick, active, children) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var cond = List.mem($$String.lowercase(children), $$Array.to_list(active));
      var activeCN = cond ? " filter-btn-active" : "";
      var className = "filter-rg-btn" + activeCN;
      return React.createElement("button", {
                  className: className,
                  onClick: onClick
                }, children);
    });
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.onClick, jsProps.active, jsProps.children);
      }));

exports.component = component;
exports.make      = make;
exports.$$default = $$default;
exports.default   = $$default;
exports.__esModule= true;
/* component Not a pure module */
