// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict'

var React = require('react')
var ReasonReact = require('reason-react/src/ReasonReact.js')

var component = ReasonReact.statelessComponent('Loader')

var loaderPath = require('../../assets/misc/loading.svg')

function make() {
    var newrecord = component.slice()
    newrecord[/* render */ 9] = function() {
        return React.createElement(
            'div',
            {
                className: 'loader center-align',
            },
            React.createElement('img', {
                className: 'loader-img',
                alt: 'Loading!',
                src: loaderPath,
            }),
        )
    }
    return newrecord
}

var $$default = ReasonReact.wrapReasonForJs(component, function() {
    return make(/* () */ 0)
})

exports.component = component
exports.loaderPath = loaderPath
exports.make = make
exports.$$default = $$default
exports.default = $$default
exports.__esModule = true
/* component Not a pure module */
