// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry       = require("bs-platform/lib/js/curry.js");
var React       = require("react");
var Caml_obj    = require("bs-platform/lib/js/caml_obj.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("PlayersSortBtn");

function grabTriString(sortKey, activeSortKey, isReversed) {
  if (sortKey === activeSortKey) {
    if (isReversed) {
      return "&#9650";
    } else {
      return "&#9660";
    }
  } else {
    return "";
  }
}

function make(onSort, sortKey, activeSortKey, isReversed, children) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var triString = grabTriString(sortKey, activeSortKey, isReversed);
      var triangle = triString.length ? React.createElement("span", {
              className: "sort-tri"
            }, triString) : null;
      var cn = "player-sort-link flash" + (
        Caml_obj.caml_equal(sortKey, activeSortKey) ? " active-sort" : ""
      );
      return React.createElement("a", {
                  className: cn,
                  href: "#",
                  onClick: (function () {
                      return Curry._1(onSort, sortKey);
                    })
                }, children, " ", triangle);
    });
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.onSort, jsProps.sortKey, jsProps.activeSortKey, jsProps.reverse, jsProps.children);
      }));

exports.component     = component;
exports.grabTriString = grabTriString;
exports.make          = make;
exports.$$default     = $$default;
exports.default       = $$default;
exports.__esModule    = true;
/* component Not a pure module */
