// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var Pervasives  = require("bs-platform/lib/js/pervasives.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("WinRate");

function colorizeWinRate(wr) {
  if (wr < 50.0) {
    return "#ff0000";
  } else if (wr < 55.0) {
    return "#ffffff";
  } else if (wr < 60.0) {
    return "#00ff00";
  } else if (wr < 65.0) {
    return "#00ccff";
  } else {
    return "#ffa500";
  }
}

function make(wins, losses, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var winRate = wins / (wins + losses) * 100.0;
      var coloredWinRate = colorizeWinRate(winRate);
      var style = {
        color: coloredWinRate
      };
      return React.createElement("span", {
                  style: style
                }, Pervasives.string_of_float(winRate));
    });
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.wins, jsProps.losses, jsProps.children);
      }));

exports.component       = component;
exports.colorizeWinRate = colorizeWinRate;
exports.make            = make;
exports.$$default       = $$default;
exports.default         = $$default;
exports.__esModule      = true;
/* component Not a pure module */
